const LOGING_INITIATED = 'LOGING_INITIATED';
const LOGING_SUCCEEDED = 'LOGING_SUCCEEDED';
const LOGING_FAILED = 'LOGING_FAILED';

const REGISTRATION_INITIATED = 'REGISTRATION_INITIATED';
const REGISTRATION_SUCCEEDED = 'REGISTRATION_SUCCEEDED';
const REGISTRATION_FAILED = 'REGISTRATION_FAILED';

export {
  LOGING_INITIATED,
  LOGING_SUCCEEDED,
  LOGING_FAILED,
  REGISTRATION_INITIATED,
  REGISTRATION_SUCCEEDED,
  REGISTRATION_FAILED,
};
